// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7q7ykCei1mFBJiVfRzw2R-gS4w4n4ZlA',
    appId: '1:327249223156:web:d9533c7b48833ac51aeda1',
    messagingSenderId: '327249223156',
    projectId: 'ici-check',
    authDomain: 'ici-check.firebaseapp.com',
    storageBucket: 'ici-check.firebasestorage.app',
    measurementId: 'G-BLT2BP7B7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsVdfrLNw1GLB2quu6bTdw2WWcyd_D5Cc',
    appId: '1:327249223156:android:0366249c5a4273641aeda1',
    messagingSenderId: '327249223156',
    projectId: 'ici-check',
    storageBucket: 'ici-check.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpKR4L0SOysN5SsEXvYShFvslsBv3Yweo',
    appId: '1:327249223156:ios:53a228c2c9f568341aeda1',
    messagingSenderId: '327249223156',
    projectId: 'ici-check',
    storageBucket: 'ici-check.firebasestorage.app',
    iosBundleId: 'com.example.iciCheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpKR4L0SOysN5SsEXvYShFvslsBv3Yweo',
    appId: '1:327249223156:ios:53a228c2c9f568341aeda1',
    messagingSenderId: '327249223156',
    projectId: 'ici-check',
    storageBucket: 'ici-check.firebasestorage.app',
    iosBundleId: 'com.example.iciCheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7q7ykCei1mFBJiVfRzw2R-gS4w4n4ZlA',
    appId: '1:327249223156:web:26860cd4448a7e131aeda1',
    messagingSenderId: '327249223156',
    projectId: 'ici-check',
    authDomain: 'ici-check.firebaseapp.com',
    storageBucket: 'ici-check.firebasestorage.app',
    measurementId: 'G-J39PBX7VM1',
  );
}
